/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PokemonFactory } from "./PokemonFactory";
export * as factories from "./factories";
export { PokemonFactory__factory } from "./factories/PokemonFactory__factory";
